# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "ProsperModelsDB"

[default.build.parameters]
cached = false
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ProsperModelsDB"
region = "us-east-1"
image_repositories = []
parameter_overrides = "FeatureListTableName=\"ProsperModels-FeatureLists\" RawDataFunctionArn=\"arn:aws:lambda:us-east-1:214666064132:function:sam-rawdata-app-RawDataFunction-ctCxAioFZKiA\" CognitoUserPoolId=\"us-east-1_LKTqOzWU4\" CognitoUserPoolClientId=\"4cqa59h596ojh3j1bsaek1tlqg\" DeploymentVersion=\"2_24\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
